### ISSUE TITLE
Allow to search caches by attributes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#327] opened 2015-07-19 16:08 UTC
```
This is an enhancement suggestion. I would like to see the possibility to 
search for caches having a specific attribute (in all or bbox requests), if 
this feature can be supported efficiently. Complicated multiple attribute 
searches would be nice, but the basic search for a single attribute present 
would be a big first step.

As a corollary (to searching for A1), searching for caches with empty gc_code 
would be nice too.
```

Original issue reported on code.google.com by `pjacobi...@googlemail.com` on 20 Nov 2014 at 9:57

**Comment by wrygiel** [comment] 2016-10-06 21:37
This is a duplicate of https://github.com/opencaching/okapi/issues/274

**Closed by wrygiel** 2016-10-06 21:37 UTC
Labels: auto-migrated, Component-CSearch, enhancement, Priority-Low
