### ISSUE TITLE
Add an option to order by date_hidden

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#292] opened 2015-07-19 16:08 UTC
```
From issue #15 by fotokubut:

Hi,
In this service we have method "order_by", but we can't ordering by date, so 
how I can do list of newest caches, like list on opencaching.pl (next to maps 
on mainsite)? When I set order_by=-code, I lose some caches (when date of 
hidden is diffrent then date of create). 

```

Original issue reported on code.google.com by `rygielski` on 17 Dec 2013 at 8:16

**Comment by following5** [comment] 2016-04-05 23:27
> In this service we have method "order_by", but we can't ordering by date, so 
how I can do list of newest caches, like list on opencaching.pl (next to maps 
on mainsite)? When I set order_by=-code, I lose some caches (when date of 
hidden is diffrent then date of create). 

date_hidden won't help either. It is the date when cache was originally placed, which can be far in the past if it das been listed at another geocaching site.

For OCDE, date_created would fit - it is updated to NOW() when the cache is published. But for OCPL it is the date when the geocache was submitted, which also may be in the past (for delayed publish).

**Comment by following5** [comment] 2016-04-05 23:45
But we may just stick to what the OC sites do on the "new caches" page.

* OCPL orders it by `GREATEST(date_hidden, date_created)`
* OCDE orders it by  `date_created`

What about calling this order "date_published", and explaining that on some sites the publication date will be _guessed_, because it is not stored in the database?

**Comment by following5** [comment] 2016-04-06 00:07
> OCPL orders it by GREATEST(date_hidden, date_created)

This however will produce funny results when searching for both event caches (where `date_hidden` is the date of the event) and non-event caches. On the OC site that's not problem, because new events are shown separately.

**Comment by following5** [comment] 2017-09-05 23:12
Oops, I opened a duplicate of this issue: #476.

Now sorting by `date_hidden` and `date_created` is available. They allow all sorting of new caches as it is currently done on the OC sites
* by `date_hidden` for the list of upcoming events
* by `date_created` for all other lists of new caches.

OCPL `date_created` is the original creation date for the listing, not the publish date. This does not give the real order of new caches, but a good estimate for most caches. A better information is not available for OCPL.

So this is solved.

**Closed by following5** 2017-09-05 23:12 UTC
Labels: auto-migrated, Component-CSearch, enhancement, Priority-Low
